export const FETCH_ALL_DATA = 'FETCH_ALL_DATA';

export const CREATE_MEMO = 'CREATE_MEMO';
export const SELECT_ITEM = 'SELECT_ITEM';
export const REMOVE_ITEMS = 'REMOVE_ITEMS';
export const UPDATE_MEMO = 'UPDATE_MEMO';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const ADD_TO_COLLECTION = 'ADD_TO_COLLECTION';
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';