export const FETCH_ALL_DATA = 'FETCH_ALL_DATA';
export const CREATE_MEMO = 'CREATE_MEMO';
export const SELECT_ITEM = 'SELECT_ITEM';
export const REMOVE_ITEMS = 'REMOVE_ITEMS';
// export const CREATE_COLLECTION = 'CREATE_COLLECTION';